### ISSUE TITLE
Question about API page size

### ISSUE THREAD

**Issue by charmingtoad** [afrayedknott/exploreRiotAPI#3]
https://github.com/afrayedknott/exploreRiotAPI/blob/769d39646b95747940881b1ebbe367984ba09ece/Main.py#L17

As a "coworker" coming into the project late I have a curiosity - how do we know the API always returns 205 records in a full page? Does the API call take in how many records are requested? Or is it just something in their documentation that says 205 is the number of results you'll get when there are more pages left to load?

**Comment by afrayedknott** [comment]
You know what, good point, it's not always going to be 205 per page probably. I suppose I'll have to do ye olde "first iter occurs outside the loop" and save that count.

**Comment by afrayedknott** [comment]
Fixed this by giving every info schema JSON a "full_page_record_count" variable which I will then fill in for each new dataset I pull. Don't need to make this dynamic since it is very unlikely to change. Or changes will be so infrequent that it's no problem to just adjust the values on the JSON.
